lib/school_portal_web/router.ex
defmodule SchoolPortalWeb.Router do
  use SchoolPortalWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SchoolPortalWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug SchoolPortal.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", SchoolPortalWeb do
    pipe_through :browser

    get "/", PageController, :index


    get "/login", SessionController, :index
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout


    get "/adminlogin", SessionAdminController, :index
    post "/adminlogin", SessionAdminController, :login
    get "/adminlogout", SessionAdminController, :logout

    resources "/users", UserController

    resources "/admins", AdminController
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SchoolPortalWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/schoolmanagementsystem_web/router.ex
defmodule SchoolmanagementsystemWeb.Router do
  use SchoolmanagementsystemWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SchoolmanagementsystemWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug SchoolmanagementsystemWeb.Plug.Authorize, :admin
  end

  pipeline :auth do
    plug Schoolmanagementsystem.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", SchoolmanagementsystemWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    resources "/registers", UserController
    resources "/admins", AdminController
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
    get "/admin-login", SessionController, :new
    post "/admin-login", SessionController, :admin_login
    get "/admin-logout", SessionController, :admin_logout
  end

  # scope "/", SchoolmanagementsystemWeb do
  #   pipe_through [:browser, :admin]
  #   resources "/users", UserController, only: [:create, :edit, :update]
  # end
  # Other scopes may use custom stacks.
  # scope "/api", SchoolmanagementsystemWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SchoolmanagementsystemWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/school_portal_web/views/layout_view.ex
defmodule SchoolPortalWeb.LayoutView do
  use SchoolPortalWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/schoolmanagementsystem_web/views/layout_view.ex
defmodule SchoolmanagementsystemWeb.LayoutView do
  use SchoolmanagementsystemWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/schoolmanagementsystem_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/schoolmanagementsystem_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/schoolmanagementsystem_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Schoolmanagementsystem", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
 
          <%= if logged_in?(@conn) do %>
            <%= current_user(@conn).email%>
            <li><span><%= link "Logout", to: Routes.session_path(@conn, :logout)%></span></li>
          <% else %>
            <li><span><%= link "Login", to: Routes.session_path(@conn, :login)%></span></li>
             <li><span><%= link "Register", to: Routes.user_path(@conn, :new)%></span></li>
          <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>